### ISSUE TITLE
[WorldEditArt] Debug TODO list

### ISSUE THREAD

**Issue by PEMapModder** [PEMapModder/Small-ZC-Plugins#7]
- [ ] Commands
  - [x] //set
    - [x] hollow
    - [x] solid
  - [x] //replace
    - [x] solid
    - [x] hollow
  - [ ] selected tools setting
  - [x] //anchor
  - [x] //cuboid
    - [x] //cuboid grow
    - [x] //cuboid shoot
  - [x] //sphere
  - [x] //cylinder
- [x] Block patterns
  - [x] Pattern parsing
    - [x] Block parsing
    - [x] Percentage parsing
  - [x] Random from map (how to test?)
- [ ] Databases
  - [ ] Player databases
    - [ ] MySQLi
    - [ ] SQLite3
    - [ ] Nested array files
  - [ ] Macro databases
    - [ ] MySQLi
    - [ ] SQLite3
    - [ ] MCR databases
  - [ ] Clipboard databases
    - [ ] MySQLi
    - [ ] SQLite3
    - [ ] CLP databases

**Comment by Bamuel** [comment]
//copy //paste 
are commands not found

**Comment by thebigsmileXD** [comment]
@Bamuel You have to enable them in the config.

**Comment by PEMapModder** [comment]
They don't even work.

**Comment by thebigsmileXD** [comment]
For me they sometimes did.

**Comment by iJoshuaHD** [comment]
@thebigsmileXD ikr xD

**Comment by 64FF00** [comment]
:'(
